version: "3"
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - common
    environment:
      NODE_ENV: production

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "lanars"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - common

volumes:
  docker-nest-postgres:
    driver: local
networks:
  common:
    driver: bridge